name:                dynahaskell
version:             0.1.0.0
github:              "isovector/dynahaskell"
license:             BSD3
author:              "Sandy Maguire"
maintainer:          "sandy@sandymaguire.me"
copyright:           "2019 Sandy Maguire"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/isovector/dynahaskell#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-exactprint
- ghc
- brick
- syb
- lens

default-extensions:
- FlexibleContexts
- GADTs
- KindSignatures
- PatternSynonyms
- ViewPatterns

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  dynahaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynahaskell

tests:
  dynahaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dynahaskell
